### ISSUE TITLE
Get-Service does not return required members for Carbon_Service on Windows Server 2012 R2 Foundation

### ISSUE THREAD

**Issue by andy1547** [pshdo/Carbon#33]
Members returned are: 
Name, RequiredServices, Disposed, Close ,Continue ,CreateObjRef, Dispose, Equals, ExecuteCommand, GetHashCode, GetLifetimeService, GetType, InitializeLifetimeService, Pause, Refresh, Start, Stop, WaitForStatus, CanPauseAndContinue, CanShutdown, CanStop, Container, DependentServices, DisplayName, MachineName, ServiceHandle, ServiceName, ServicesDependedOn, ServiceType, Site, StartType, Status, ToString

This means the TestScript always returns $false when specifying unsupported keys such as OnFirstFailure.

**Comment by splatteredbits** [comment]
I'm unable to reproduce this issue on `Microsoft Windows Server 2012 R2 Standard`. I don't have access to `Windows Server 2012 R2 Foundation`. (I'd never heard of it until this issue.) 

After I import Carbon and get a service, I see the `FirstFailure` method.

    > Import-Module Carbon
    > get-service | get-member


    TypeName: System.ServiceProcess.ServiceController

    Name                      MemberType     Definition
    ----                      ----------     ----------
    Name                      AliasProperty  Name = ServiceName
    RequiredServices          AliasProperty  RequiredServices = ServicesDependedOn
    Disposed                  Event          System.EventHandler Disposed(System.Object, System.EventArgs)
    Close                     Method         void Close()
    Continue                  Method         void Continue()
    CreateObjRef              Method         System.Runtime.Remoting.ObjRef CreateObjRef(type requestedType)
    Dispose                   Method         void Dispose(), void IDisposable.Dispose()
    Equals                    Method         bool Equals(System.Object obj)
    ExecuteCommand            Method         void ExecuteCommand(int command)
    GetHashCode               Method         int GetHashCode()
    GetLifetimeService        Method         System.Object GetLifetimeService()
    GetType                   Method         type GetType()
    InitializeLifetimeService Method         System.Object InitializeLifetimeService()
    Pause                     Method         void Pause()
    Refresh                   Method         void Refresh()
    Start                     Method         void Start(), void Start(string[] args)
    Stop                      Method         void Stop()
    WaitForStatus             Method         void WaitForStatus(System.ServiceProcess.ServiceControllerStatus desiredStatus), void WaitForStatus(System.ServiceProcess.ServiceControllerStatus desiredStatus, timespan timeout)
    CanPauseAndContinue       Property       bool CanPauseAndContinue {get;}
    CanShutdown               Property       bool CanShutdown {get;}
    CanStop                   Property       bool CanStop {get;}
    Container                 Property       System.ComponentModel.IContainer Container {get;}
    DependentServices         Property       System.ServiceProcess.ServiceController[] DependentServices {get;}
    DisplayName               Property       string DisplayName {get;set;}
    MachineName               Property       string MachineName {get;set;}
    ServiceHandle             Property       System.Runtime.InteropServices.SafeHandle ServiceHandle {get;}
    ServiceName               Property       string ServiceName {get;set;}
    ServicesDependedOn        Property       System.ServiceProcess.ServiceController[] ServicesDependedOn {get;}
    ServiceType               Property       System.ServiceProcess.ServiceType ServiceType {get;}
    Site                      Property       System.ComponentModel.ISite Site {get;set;}
    Status                    Property       System.ServiceProcess.ServiceControllerStatus Status {get;}
    GetServiceConfigProperty  ScriptMethod   System.Object GetServiceConfigProperty();
    ToString                  ScriptMethod   System.Object ToString();
    Description               ScriptProperty System.Object Description {get=$this.GetServiceConfigProperty( 'Description' );}
    ErrorControl              ScriptProperty System.Object ErrorControl {get=$this.GetServiceConfigProperty( 'ErrorControl' );}
    FailureProgram            ScriptProperty System.Object FailureProgram {get=$this.GetServiceConfigProperty( 'FailureProgram' );}
    FirstFailure              ScriptProperty System.Object FirstFailure {get=$this.GetServiceConfigProperty( 'FirstFailure' );}
    LoadOrderGroup            ScriptProperty System.Object LoadOrderGroup {get=$this.GetServiceConfigProperty( 'LoadOrderGroup' );}
    Path                      ScriptProperty System.Object Path {get=$this.GetServiceConfigProperty( 'Path' );}
    RebootDelay               ScriptProperty System.Object RebootDelay {get=$this.GetServiceConfigProperty( 'RebootDelay' );}
    RebootDelayMinutes        ScriptProperty System.Object RebootDelayMinutes {get=$this.GetServiceConfigProperty( 'RebootDelayMinutes' );}
    RebootMessage             ScriptProperty System.Object RebootMessage {get=$this.GetServiceConfigProperty( 'RebootMessage' );}
    ResetPeriod               ScriptProperty System.Object ResetPeriod {get=$this.GetServiceConfigProperty( 'ResetPeriod' );}
    ResetPeriodDays           ScriptProperty System.Object ResetPeriodDays {get=$this.GetServiceConfigProperty( 'ResetPeriodDays' );}
    RestartDelay              ScriptProperty System.Object RestartDelay {get=$this.GetServiceConfigProperty( 'RestartDelay' );}
    RestartDelayMinutes       ScriptProperty System.Object RestartDelayMinutes {get=$this.GetServiceConfigProperty( 'RestartDelayMinutes' );}
    RunCommandDelay           ScriptProperty System.Object RunCommandDelay {get=$this.GetServiceConfigProperty( 'RunCommandDelay' );}
    RunCommandDelayMinutes    ScriptProperty System.Object RunCommandDelayMinutes {get=$this.GetServiceConfigProperty( 'RunCommandDelayMinutes' );}
    SecondFailure             ScriptProperty System.Object SecondFailure {get=$this.GetServiceConfigProperty( 'SecondFailure' );}
    StartMode                 ScriptProperty System.Object StartMode {get=$startType = $this.GetServiceConfigProperty( 'StartType' )...
    StartType                 ScriptProperty System.Object StartType {get=$this.GetServiceConfigProperty( 'StartType' );}
    TagID                     ScriptProperty System.Object TagID {get=$this.GetServiceConfigProperty( 'TagID' );}
    ThirdFailure              ScriptProperty System.Object ThirdFailure {get=$this.GetServiceConfigProperty( 'ThirdFailure' );}
    UserName                  ScriptProperty System.Object UserName {get=$this.GetServiceConfigProperty( 'UserName' );}

**Comment by splatteredbits** [comment]
Closing as I haven't heard back from original reporter and I'm unable to reproduce.
