### ISSUE TITLE
WmiPrvSe.exe Process locks files in Carbon Module

### ISSUE THREAD

**Issue by mmcelreath** [pshdo/Carbon#36]
We are using a couple DSC resources from Carbon in out DSC configurations and I have noticed in the past that on servers running DSC, we couldn't delete the Carbon module if we needed to because files were in use. I ran Process Explorer on one of the servers and the WmiPrvSE.exe process is in fact using several files from the Carbon module, even after the consistency check has completed. Specifically, the following files are being used:

\Carbon\2.2.0\bin\Carbon.lis.dll
\Carbon\2.2.0\bin\Carbon.dll
\Carbon\2.2.0\bin\Ionic.Zip.dll

These files stay in use for at least a few minutes (maybe longer) after a consistency check runs, making the module hard to delete.We have some other custom resources that were developed in house where this is not the case. No files get locked up during or after the consistency check. I'm not sure if this is a Carbon specific thing or a PowerShell/DSC specific thing.

**Comment by mmcelreath** [comment]
We are running Carbon version 2.2.0

**Comment by splatteredbits** [comment]
This, unfortunately, is the way PowerShell works. Carbon ships with an assembly and when PowerShell loads that assembly, it locks it to prevent others from writing to it. The only way to unlock it is to close all processes that unlock it.

The only way to work around this is to copy the assemblies to a temporary location and load them from there. While that would work, I'd have to 1) remove the assemblies from the Carbon module manifest and 2) load them by hand when the module gets loaded.

Pull requests accepted!

**Comment by lankaapura** [comment]
@mmcelreath  I'm using the following workaround now, not elegant but it works. @splatteredbits  I can send a PR if you can guide me.
```
    Copy-Item ".\Tools\Carbon\" "C:\Temp\Tools\Carbon\" -Recurse -Force -ErrorAction SilentlyContinue
    if ($setup_iis -and (Test-Path  C:\Temp\Tools\Carbon\Import-Carbon.ps1)) {     
        C:\Temp\Tools\Carbon\Import-Carbon.ps1
        $script:setup_iis = $true
    }else{
        $script:setup_iis = $false
    }
```

**Comment by splatteredbits** [comment]
> We are using a couple DSC resources from Carbon in out DSC configurations and I have noticed in the past that on servers running DSC, we couldn't delete the Carbon module if we needed to because files were in use. I ran Process Explorer on one of the servers and the WmiPrvSE.exe process is in fact using several files from the Carbon module, even after the consistency check has completed. Specifically, the following files are being used:
> 
> \Carbon\2.2.0\bin\Carbon.lis.dll
> \Carbon\2.2.0\bin\Carbon.dll
> \Carbon\2.2.0\bin\Ionic.Zip.dll
> 
> These files stay in use for at least a few minutes (maybe longer) after a consistency check runs, making the module hard to delete.We have some other custom resources that were developed in house where this is not the case. No files get locked up during or after the consistency check. I'm not sure if this is a Carbon specific thing or a PowerShell/DSC specific thing.

**Comment by splatteredbits** [comment]
I'm closing this as this is a feature of PowerShell and DSC. Any/all DSC resources that use modules that ship with assemblies will have the same issue.
